/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('antdv-next')['Avatar']
    AButton: typeof import('antdv-next')['Button']
    AConfigProvider: typeof import('antdv-next')['ConfigProvider']
    ADrawer: typeof import('antdv-next')['Drawer']
    AEmpty: typeof import('antdv-next')['Empty']
    AFloatButton: typeof import('antdv-next')['FloatButton']
    AQrcode: typeof import('antdv-next')['QRCode']
    ASpace: typeof import('antdv-next')['Space']
    ATag: typeof import('antdv-next')['Tag']
    DanmakuList: typeof import('./components/DanmakuList.vue')['default']
    LoginPanel: typeof import('./components/LoginPanel.vue')['default']
    UserPanel: typeof import('./components/UserPanel.vue')['default']
  }
}
